# Generated by Django 2.1.7 on 2019-03-14 08:30

from django.db import migrations, models
import stasher.customers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.TextField(default=stasher.customers.models._default_id, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('gender', models.CharField(max_length=1)),
                ('country_code', models.CharField(max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
